version: '3.8'

services:
  backend_1:
    build: './backend'
    environment:
      MYSQL_URL: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'akitainu'
      MYSQL_DB: 'exploding_puppy'
      SERVER_PORT: '8000'
      SOCKET_PORT: '10002'
    ports:
      - 8000:8000
      - 10002:10002
    restart: always
  backend_2:
    build: './backend'
    environment:
      MYSQL_URL: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'akitainu'
      MYSQL_DB: 'exploding_puppy'
      SERVER_PORT: '9000'
      SOCKET_PORT: '10003'
    ports:
      - 9000:9000
      - 10003:10003
    restart: always
  db:
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: akitainu
      MYSQL_DATABASE: exploding_puppy
    command: --init-file /data/application/init.sql
    volumes:
      - ./db:/data/application
      - db-data:/var/lib/mysql
    restart: always
  nginx:
    build: './nginx'
    ports:
      - 10000:10000
      - 10001:10001
volumes:
  db-data:
